# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - 610amigo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_17953a925d8140b3927c1cd082de068f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0883236d864f476e96f1e4ab2a7386b3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_17953a925d8140b3927c1cd082de068f }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: '610amigo'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ab4771e7b6334c0d9d406dd97866efd2 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_17953a925d8140b3927c1cd082de068f }}/appsvc/staticsite:${{ github.sha }}'